### ISSUE TITLE
ngAnnotate appears to not overwrite files

### ISSUE THREAD

**Issue by rwwagner90** [mzgol/grunt-ng-annotate#25] opened 2015-02-10 04:50 UTC
I'm trying to use this, and my files don't seem to be annotated when I view them. 
```js
ngAnnotate: {
      options: {
        singleQuotes: true
      },
      dist: {
        files: [{
          expand: true,
          cwd: '.tmp/concat/scripts',
          src: '*.js',
          dest: '.tmp/concat/scripts'
        }]
      }
    },
```
However, if I add:
```js
          ext: '.annotated.js',
```

Then I can see the annotation in the file. What's the deal here?

**Comment by mzgol** [comment] 2015-02-19 13:50
Works for me. Are you sure you have correctly set up paths?

I've added a test ensuring overwriting files works: https://github.com/mzgol/grunt-ng-annotate/commit/d6e2684111d018d0f6f7f07848ad8a35c51f65e1

**Comment by mzgol** [comment] 2015-02-19 14:16
I'll close it for now since I have a test ensuring this works (I even tried with config similar to yours and it worked as well) so I'm pretty sure the issue is on your end. If you have a test case proving otherwise, please share it so that I can look at it.

**Closed by mzgol** 2015-02-19 14:16 UTC
